config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Sidekiq::Web => '/sidekiq'

  root to: 'home#index'

  devise_for :users, controllers: {
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  get 'accounts/amazon', to: 'accounts#amazon'
  patch 'profile/:id', to: 'profiles#update', as: 'profile'
end

app/models/account.rb
# == Schema Information
#
# Table name: accounts
#
#  id           :bigint           not null, primary key
#  name         :string
#  account_type :string
#  external_id  :string
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  region_id    :bigint           not null
#
class Account < ApplicationRecord
  belongs_to :region
  has_many :profiles
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  def amazon
    @profile_metrics = ProfileMetricSummary.includes(profile: [:marketplace, :account]).order('accounts.name')
    @profile_metrics = @profile_metrics.where('accounts.name ilike ? or marketplaces.country_code ilike ? or accounts.account_type ilike ?', "%#{params[:q]}%", "%#{params[:q]}%", "%#{params[:q]}%") if params[:q].present?
    @profile_metrics = @profile_metrics.where('accounts.account_type = ?', params[:account_type]) if params[:account_type].present?
    @profile_metrics = @profile_metrics.where('profiles.is_actively_managed = ?', params[:is_actively_managed]) if params[:is_actively_managed].present?
    if params[:range]

    end
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper

  def profile_name(profile)
    profile ? "#{profile&.account&.name} - #{profile&.marketplace&.country_code}" : ""
  end

  def cost_per_click(metric)
    "$#{(metric.cost / metric.clicks).round(2)}"
  end

  def acost(metric)
    "#{(metric.cost/metric.sales_14d).round(2)}%"
  end

  def account_type_select_options
    unique_account_types = Account.pluck(:account_type).uniq # ["seller", "vendor"]
    unique_account_types.map{|type| [type.titleize, type]}.unshift ['Show All', ""]
    #[["Show All", ""], ["Seller", "seller"], ["Vendor", "vendor"]]
  end

  def managed_status_select_options
    [["Show All", ""], ["Managed", true], ["Unmanaged", false]]
  end

  def data_range_select_options
    preset_range = [7, 14, 30, 60]
    select_options = preset_range.map{|range| ["Last #{range} Days", range]}
    #[["Last 7 Days", 7], ["Last 14 Days", 14], ["Last 30 Days", 30], ["Last 60 Days", 60]]
    select_options.unshift ["Show All", ""]
  end
end

app/views/accounts/_profile_metrics.html.erb
<div id="kt_table_widget_4_table_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
  <div class="table-responsive">
    <table class="table align-middle table-row-dashed fs-6 gy-3 no-footer" id="kt_table_widget_4_table">
      <!--begin::Table head-->
      <thead>
      <!--begin::Table row-->
      <tr class="text-start text-gray-400 fw-bold fs-7 text-uppercase gs-0">
        <th class="sorting_disabled" rowspan="1" colspan="1" style="width: 180.1px;">Name</th>
        <th class="text-end sorting_disabled" rowspan="1" colspan="1" style="width: 102.1px;">Type</th>
        <th class="text-end sorting_disabled" rowspan="1" colspan="1" style="width: 125.3px;">Impressions</th>
        <th class="text-end sorting_disabled" rowspan="1" colspan="1" style="width: 100px;">Clicks</th>
        <th class="text-end sorting_disabled" rowspan="1" colspan="1" style="width: 133.28px;">CTR</th>
        <th class="text-end sorting_disabled" rowspan="1" colspan="1" style="width: 102.3px;">Avg CPC</th>
        <th class="text-end sorting_disabled" rowspan="1" colspan="1" style="width: 91.25px;">Cost</th>
        <th class="text-end sorting_disabled" rowspan="1" colspan="1" style="width: 91.25px;">Orders</th>
        <th class="text-end sorting_disabled" rowspan="1" colspan="1" style="width: 91.25px;">Sales</th>
        <th class="text-end sorting_disabled" rowspan="1" colspan="1" style="width: 25.6667px;">ACo5%</th>
        <th class="text-end sorting_disabled" rowspan="1" colspan="1" style="width: 25.6667px;">Managed</th>
      </tr>
      <!--end::Table row-->
      </thead>
      <!--end::Table head-->
      <!--begin::Table body-->
      <tbody class="fw-bold text-gray-600">
      <% @profile_metrics.each_with_index do |metric, indx|  %>
        <% profile = metric.profile %>
        <tr class="<%= indx.odd? ? "odd" : "even"  %>">
          <td class="text-gray-800 text-hover-primary"><%= profile_name(profile) %></td>
          <td class="text-end"><%= profile&.account&.account_type&.titleize %></td>
          <td class="text-end"><%= metric.impressions %></td>
          <td class="text-end"><%= metric.clicks %></td>
          <td class="text-end"><%= metric.click_through_rate&.round(5) %></td>
          <td class="text-end"><%= cost_per_click(metric) %></td>
          <td class="text-end"><%= "$#{metric.cost}" %></td>
          <td class="text-end"><%= metric.purchases_14d %></td>
          <td class="text-end"><%= metric.sales_14d %></span></td>
          <td class="text-end"><%= acost(metric)%></span></td>
          <td class="text-end">
            <div class="form-check form-switch form-check-custom form-check-success form-check-solid">
              <%= form_for(profile) do |f| %>
                <%= f.check_box :is_actively_managed, class: "form-check-input h-20px w-40px",value:"", id:"kt_flexSwitchCustomDefault_1_1", onchange: "this.form.requestSubmit()" %>
              <% end %>
            </div>
          </td>
        </tr>
      <% end %>
      </tbody>
      <!--end::Table body-->
    </table>
  </div>
  <div class="row">
    <div class="col-sm-12 col-md-5 d-flex align-items-center justify-content-center justify-content-md-start"></div>
    <div class="col-sm-12 col-md-7 d-flex align-items-center justify-content-center justify-content-md-end"></div>
  </div>
</div>

app/views/accounts/amazon.html.erb
<%= render partial: "shared/toolbar", locals: {title: "Amazon Dashboard", breadcrumbs: %w(Accounts Amazon) } %>
<div class="row gy-5 g-xl-10">

  <div class="col-xl-12 mb-5 mb-xl-12">
    <div class="card card-flush h-xl-100">
      <div class="card-header pt-7">
      <h3 class="card-title align-items-start flex-column">
        <span class="card-label fw-bold text-gray-800">List of Accounts</span>
      </h3>
      <div class="card-toolbar">
        <%= form_with url: accounts_amazon_path, method: :get, data: { controller: "profile-search-form", profile_search_form_target: "form", turbo_frame: "profile_metrics" }  do |form| %>
          <div class="d-flex flex-stack flex-wrap gap-4">
            <div class="d-flex align-items-center fw-bold">
              <div class="text-gray-400 fs-7 me-2">Type</div>
                <%= form.select :account_type, account_type_select_options,
                                {:selected => params[:account_type]},
                                {class: "select2-form form-select form-select-transparent text-graY-800 fs-base lh-1 fw-bold py-0 ps-3 w-auto",
                                 "data-control": "select2", "data-hide-search": true,
                                 "data-dropdown-css-class": "w-150px",
                                 data: {action: "change->profile-search-form#search"},
                                }
                %>
            </div>

            <div class="d-flex align-items-center fw-bold">
              <div class="text-gray-400 fs-7 me-2">Status</div>
              <%= form.select :is_actively_managed, managed_status_select_options,
                              {:selected => params[:is_actively_managed]},
                              {class: "select2-form form-select form-select-transparent text-graY-800 fs-base lh-1 fw-bold py-0 ps-3 w-auto",
                               "data-control": "select2", "data-hide-search": true,
                               "data-dropdown-css-class": "w-150px",
                               "data-kt-table-widget-4": "filter_status",
                               "data-action": "change->profile-search-form#search",
                              }
              %>
            </div>

            <div class="d-flex align-items-center fw-bold">
              <div class="text-gray-400 fs-7 me-2"><i class="ki-outline ki-calendar-add fs-1"></i></div>
              <%= form.select :date_range, data_range_select_options,
                              {:selected => params[:date_range]},
                              { class: "select2-form form-select form-select-transparent text-graY-800 fs-base lh-1 fw-bold py-0 ps-3 w-auto",
                               "data-control": "select2", "data-hide-search": true,
                               "data-dropdown-css-class": "w-150px",
                               "data-action": "onchange->profile-search-form#search",
                               }
              %>
            </div>
            <div class="position-relative my-1">
              <i class="ki-duotone ki-magnifier fs-2 position-absolute top-50 translate-middle-y ms-4">
                <span class="path1"></span>
                <span class="path2"></span>
              </i>
              <%= form.text_field :q,
                                  class: "form-control w-150px fs-7 ps-12",
                                  placeholder: "Search",
                                  data: { action: "input->profile-search-form#search" }
              %>
            </div>
          </div>
        <% end %>
      </div>
    </div>

    <div class="card-body pt-2">
      <%= turbo_frame_tag "profile_metrics", data: { turbo_action: :advance } do %>
        <%= render partial: 'profile_metrics' %>
      <% end %>
    </div>
  </div>
 </div>
</div>